version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for ObtainEMLLambda."

  build:
    commands:
      - echo "Packaging Lambda Function: ObtainEMLLambda"
      # Cambiar a la carpeta específica de la función
      - cd ObtainEMLLambda
      # Comprimir los archivos de la función en un archivo ZIP
      - zip -r ../ObtainEMLLambda.zip .

  post_build:
    commands:
      - echo "Deploying Lambda Function: ObtainEMLLambda"
      # Actualizar explícitamente el código de la función en AWS Lambda
      - aws lambda update-function-code \
          --function-name ObtainEMLLambda \
          --zip-file fileb://ObtainEMLLambda.zip

artifacts:
  files:
    - ObtainEMLLambda.zip
